# Generated by Django 3.0 on 2021-07-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=30)),
                ('carmodel', models.IntegerField()),
                ('carcolor', models.CharField(max_length=20)),
                ('carprice', models.IntegerField()),
            ],
        ),
    ]
