# Generated by Django 3.0 on 2021-07-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='carimage',
            field=models.ImageField(default='defaultcar.jpg', upload_to='carimage/'),
        ),
    ]
