# Generated by Django 3.0 on 2021-07-18 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_cars_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='buycar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('carname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.cars')),
            ],
        ),
    ]
