# Generated by Django 3.0 on 2021-07-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_buycar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buycar',
            name='carname',
        ),
    ]
