# Generated by Django 3.0 on 2021-07-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_remove_buycar_carname'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='ccolor',
            field=models.CharField(default='carcolour', max_length=20),
        ),
        migrations.AddField(
            model_name='buycar',
            name='cmodel',
            field=models.IntegerField(default='2021'),
        ),
        migrations.AddField(
            model_name='buycar',
            name='cnames',
            field=models.CharField(default='carnames', max_length=20),
        ),
        migrations.AddField(
            model_name='buycar',
            name='cprice',
            field=models.IntegerField(default='1000000'),
        ),
    ]
